### ISSUE TITLE
The pagination allows users to go beyond the last page of wallpapers

### ISSUE THREAD

**Issue by Prajwalshinde777** [xtremeandroid/HeavenWalls-WallPaperApp#2]
**Bug**
When navigating through the pages of wallpapers, the pagination allows users to go beyond the last page of wallpapers.

**To Reproduce**
1. Go to the page with wallpapers
2. Click on the pagination control to go to the next page
3. Continue clicking until you go beyond the last page of wallpapers

**Expected behavior**
The pagination should not allow users to go beyond the last page of wallpapers. It should either disable the "Next" button or show a message indicating that there are no more wallpapers.

**Actual behavior**
The pagination allows users to continue going to pages beyond the last page of wallpapers.

**Screenshots**

<img width="960" alt="thorium_wfKphIYDgJ" src="https://github.com/xtremeandroid/heavenWalls/assets/77891752/d8577dd8-eb4a-476f-9656-d4ad43ef55fc">

**Comment by xtremeandroid** [comment]
Assigned this issue to you, you can work on this issue

**Comment by xtremeandroid** [comment]
Resolved Now ! 


<img width="960" alt="chrome_V7tMvYbaoc" src="https://github.com/xtremeandroid/heavenWalls/assets/62198074/44021b35-3a59-4f27-b97b-5d49982fbeaa">
